on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  doc-build:
    name: Doc Build
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install graphviz
        run: |
         sudo apt-get update -y
         sudo apt-get install -y graphviz pandoc

      - uses: actions/checkout@v4
        with:
           path: tib

      - uses: "actions/setup-python@v5"
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        working-directory: tib
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Create virtual env
        working-directory: tib
        run: |
          uv venv ~/env-tib -p python${{ matrix.python-version }}
          uv pip install -p ~/env-tib -r requirements.txt

      - name: Build docs
        shell: bash -l {0}
        working-directory: tib
        run: |
          source ~/env-tib/bin/activate
          make github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tib/docs
          publish_branch: gh-pages
